# ----------------------- #
#      Site Settings      #
# ----------------------- #

title: Freedom Highway
email: 
description: Guides to Life
url: "https://paper-engineer.github.io"
baseurl: "/guides-to-life"
timezone: NZ

author: 
copyright: 'Copyright &copy; 2024 CC BY'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: 
exclude: [".gitignore", "LICENSE", "README.md"]

remote_theme: 

kramdown:
  input: GFM
sass:
  style: compressed
  
# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

#social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap
#  - title: linkedin
#    url: 
