# Site settings
title: Freedom Highway
email: 
description: Guides to Life
url: "https://paper-engineer.github.io"
baseurl: "/guides-to-life"
timezone: NZ

# Build settings - do not change
remote_theme: adamrehn/jekyll-theme-gitbook@v0.0.1
markdown: kramdown
kramdown:
  input: GFM
exclude: [".gitignore", "LICENSE", "README.md"]
sass:
  style: compressed

# Only needed for local development, will be enabled automatically by GitHub Pages
plugins: ["jekyll-remote-theme"]

# Theme settings
theme-settings:
  # Copyright settings
  copyright:
    author: Big Mog & Little Mog
    license: "CC BY 4.0"
    year: 2025
  # The collection that contains our chapters
  collection: chapters
  # Enable generation of links for chapter index pages
  indices: false

# Configure the permalinks for each chapter
collections_dir: _collections
collections:
  chapters:
    output: true
    permalink: /:path

# Use front matter defaults to supply the metadata for each chapter
defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "default"
      toc: true
  -
    scope:
      path: "_collections/_chapters/0-introduction"
    values:
      chapter: "Introduction"
      chapnum: 1
      subsite: "Young Person's Guide"
  -
    scope:
      path: "_collections/_chapters/first-chapter"
    values:
      chapter: "Logistics"
      chapnum: 2
      subsite: "Young Person's Guide"
  -
    scope:
      path: "_collections/_chapters/second-chapter"
    values:
      chapter: "Second Chapter"
      chapnum: 3
      subsite: "Young Person's Guide"
  -
    scope:
      path: "_collections/_chapters/third-chapter"
    values:
      chapter: "Third Chapter"
      chapnum: 4
      subsite: "Adult's Guide"
